# -*- coding: utf-8 -*-
"""Integracion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeoKef7ioUshLxhxERJ5G4I76Ho-j6p1
"""

# ==============================
# ETL FINAL - 2616282020
# ==============================

import pandas as pd

# ------------------------------
# 1. LEER DESDE GITHUB
# ------------------------------

dept = pd.read_csv("https://raw.githubusercontent.com/iJahir/etl-data-pipeline-25168282020-/refs/heads/main/data/curated/curated_departamentos.csv")
emp  = pd.read_csv("https://raw.githubusercontent.com/iJahir/etl-data-pipeline-25168282020-/refs/heads/main/data/curated/curated_empleados.csv")
sal  = pd.read_csv("https://raw.githubusercontent.com/iJahir/etl-data-pipeline-25168282020-/refs/heads/main/data/curated/curated_salarios.csv")

print("✅ Archivos cargados")


# ------------------------------
# 2. LIMPIAR COLUMNAS
# ------------------------------

dept.columns = dept.columns.str.strip().str.lower()
emp.columns  = emp.columns.str.strip().str.lower()
sal.columns  = sal.columns.str.strip().str.lower()


# ------------------------------
# 3. LIMPIEZA DE DATOS
# ------------------------------

# convertir a numéricos
dept["dept"] = pd.to_numeric(dept["dept"], errors="coerce")

emp["id"] = pd.to_numeric(emp["id"], errors="coerce")
emp["dept"] = pd.to_numeric(emp["dept"], errors="coerce")

sal["id"] = pd.to_numeric(sal["id"], errors="coerce")
sal["salario"] = pd.to_numeric(sal["salario"], errors="coerce")

# eliminar nulos
dept = dept.dropna()
emp  = emp.dropna()
sal  = sal.dropna()

print("✅ Datos limpios")


# ------------------------------
# 4. INTEGRACIÓN (LEFT JOIN)
# ------------------------------

df = emp.merge(dept, on="dept", how="left")
df = df.merge(sal, on="id", how="left")

print("✅ Integración realizada")


# ------------------------------
# 5. LIMPIAR COLUMNAS DUPLICADAS
# ------------------------------

df = df.rename(columns={"nombre_x": "nombre"})
df = df.drop(columns=["nombre_y"], errors="ignore")


# ------------------------------
# 6. RESULTADO FINAL
# ------------------------------

print("\nPreview:")
print(df.head())

print("\nShape:", df.shape)


# ------------------------------
# 7. GUARDAR ARCHIVO
# ------------------------------

df.to_csv("dataset_final.csv", index=False)

print("\n✅ Archivo generado: dataset_final.csv")


# ------------------------------
# 8. DESCARGAR (COLAB)
# ------------------------------

from google.colab import files
files.download("dataset_final.csv")

print("\n🚀 ETL COMPLETO FINALIZADO")

import pandas as pd
from sqlalchemy import create_engine

# 1. Leer tu dataset final
df = pd.read_csv("dataset_final.csv")

# 2. Conexión a Render (USA EXTERNAL DATABASE URL)
engine = create_engine("postgresql://etl_user:g8osc98JrWZDNMXLphvLipy8J2yaBA5c@dpg-d6qvats50q8c73bpu3i0-a.oregon-postgres.render.com/etl_seguros_04xg")

# 3. Subir datos
df.to_sql("empleados_final", engine, if_exists="replace", index=False)

print("Datos cargados correctamente a Render")

df_test = pd.read_sql_query("SELECT * FROM empleados_final", engine)
print(df_test)

from google.colab import files
files.download('dataset_final.csv')